---
title: 'Women''s Work 2022: Identifying Promising Occupations'
author: "Kara Haberstock Tanoue"
date: "2022-10-07"
output: html_document
---

### Purpose

In 2019, the CRED Team, in partnership with the Women's Foundation, published a white paper titled [*Women's Work: Realities and Possibilities for Arizona*](https://womengiving.org/wp-content/uploads/2022/01/WFSA-2019-research_Womens-Work.pdf). This paper identified mid-skill high-wage fields as promising options for workers in Arizona looking for careers that enable self-sufficiency and provided evidence-based suggestions on how to support women pursuing mid-skill, high-wage jobs, often in non-traditional fields. This project seeks to update that work in light of the economic disruption and labor market changes precipitated by the COVID-19 pandemic.

### Methods for Identifying Promising Occupations

#### Sources

To identify mid-skill, high-wage occupations, we used 3 different employment datasets produced by the Bureau of Labor Statistics (BLS) and the Arizona Office of Economic Opportunity (OEO).

-   [BLS Occupational and Wage Statistics (OEWS)](https://www.bls.gov/oes/home.htm): We used the May 2021 State OEWS for the state of Arizona, accessed from the [OEWS Data page](https://www.bls.gov/oes/tables.htm). This dataset provides wage data for detailed occupations based on a national survey of employers.
-   [BLS Employment Projections (EP)](https://www.bls.gov/emp/): We used the Sept 2021 Education and Training table, accessed from the [EP data page](https://www.bls.gov/emp/tables.htm). This dataset provides education and training requirements for detailed occupations based on the National Employment Matrix.\
-   [OEO Employment Projections](https://www.azcommerce.com/oeo/labor-market/employment-projections/): We used the 2020-2030 Occupation Projections, accessed from the [main page](https://www.azcommerce.com/oeo/labor-market/employment-projections/). This dataset provides 10-year job growth projections for the state of Arizona.

#### Process

1.  Download and prep required datasets. Strip out table annotations and save XLS files as CSVs a folder titled "raw-data."
2.  Load, clean, and merge occupation datasets from BLS and OEO using `scripts/01-extract-clean-BLS-data.R`. This script will give you a cleaned and merged dataset `clean-data/az_occdata_may21.csv`
3.  Filter occupation dataset based on promising occupation criteria using `scripts/02-filter-BLS-data.R`. This script will give you a filtered promising occupation dataset `clean-data/az_promising_occupations21.csv`

### Promising Occupations in Arizona: Initial List

```{r}
## This does not currently work-- check back on methods for relative paths in rmarkdown
library(tidyverse)
data <- read.csv("clean-data/promising_occupations21.csv")


```

This initial filtering identified `r length(unique(data$OCC_CODE))` promising occupations

